[mypy]
python_version = 3.13
plugins = pydantic.mypy
follow_imports = silent
warn_redundant_casts = True
warn_unused_ignores = True
disallow_any_generics = True
check_untyped_defs = True
disallow_untyped_defs = True

[mypy-dbus.*]
ignore_missing_imports = True

[mypy-authlib.*]
ignore_missing_imports = True

[mypy-pamela.*]
ignore_missing_imports = True

[pydantic-mypy]
init_typed = True
warn_untyped_fields = True
[mypy-psutil.*]
ignore_missing_imports = True
