"""Initial migration

Revision ID: 6b98c9fd8477
Revises: 
Create Date: 2025-01-25 00:14:24.486563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b98c9fd8477'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_activity_recent')
    op.drop_table('device_activity')
    op.drop_table('devices')
    op.drop_table('signing_keys')
    op.drop_table('tokens')
    op.drop_table('device_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_stats',
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('request_count', sa.INTEGER(), nullable=False),
    sa.Column('error_count', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_count', sa.INTEGER(), nullable=False),
    sa.Column('last_activity', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='fk_device_stats_device_id_devices'),
    sa.PrimaryKeyConstraint('device_id', name='pk_device_stats')
    )
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('key_id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='fk_tokens_device_id_devices'),
    sa.ForeignKeyConstraint(['key_id'], ['signing_keys.id'], name='fk_tokens_key_id_signing_keys'),
    sa.PrimaryKeyConstraint('id', name='pk_tokens'),
    sa.UniqueConstraint('token', name='uq_tokens_token')
    )
    op.create_table('signing_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_signing_keys'),
    sa.UniqueConstraint('key', name='uq_signing_keys_key')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('first_seen', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('device_id', name='pk_devices')
    )
    op.create_table('device_activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), nullable=False),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='fk_device_activity_device_id_devices'),
    sa.PrimaryKeyConstraint('id', name='pk_device_activity')
    )
    op.create_table('device_activity_recent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), nullable=False),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='fk_device_activity_recent_device_id_devices'),
    sa.PrimaryKeyConstraint('id', name='pk_device_activity_recent')
    )
    # ### end Alembic commands ###