"""System schemas."""

from .system import (
    BatteryInfo,
    DateTimeInfo,
    DeviceInfo,
    DeviceModel,
    DeviceStats,
    FailedService,
    FailedServices,
    Health,
    HotspotClients,
    HotspotCredentials,
    LoadAverage,
    NtpAutoInfo,
    NtpInfo,
    NtpSetRequest,
    NtpStatus,
    PowerActionResponse,
    RegDomainInfo,
    RegDomainList,
    RegDomainSetRequest,
    RfkillState,
    ServiceRunning,
    ServiceStatus,
    SwapUsage,
    TemperatureReading,
    ThrottleInfo,
    TimezoneInfo,
    TimezoneList,
    TimezoneSetRequest,
)
