from .system import (
    BatteryInfo,
    DateTimeInfo,
    DeviceInfo,
    DeviceModel,
    DeviceStats,
    RegDomainInfo,
    RegDomainList,
    RegDomainSetRequest,
    ServiceRunning,
    ServiceStatus,
    TimezoneInfo,
    TimezoneList,
    TimezoneSetRequest,
)
